version: "3"

services:
  backend:
    build: ./task-manager-backend
    ports:
      - "3000:3000"

  frontend:
    build: ./task-manager-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend